### ISSUE TITLE
jupyter

### ISSUE THREAD

**Issue by GunSik2** [GunSik2/k8s-ai#22]
k8s + jupyter

Jupyter 배포
- longhorn 스토리지클래스 사용 
- jlab 네임스페이스 사용 
- deepo.jlab.14.49.xxx.xxx.xip.io 호스트명 사용
- deepo.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepo-pvc
  namespace: jlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepo
  namespace: jlab
  labels:
    name: deepo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deepo
  template:
    metadata:
      labels:
        name: deepo
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: deepo
        image: ufoym/deepo:all-jupyter-py36-cu100
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        command:
        - /bin/bash
        - -c
        - |
          jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='xxxx' --notebook-dir='/root'
        volumeMounts:
        - name: deepo-data
          mountPath: /root
        resources:
          requests:
            memory: 500Mi
            cpu: 250m
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Always
      volumes:
      - name: deepo-data
        persistentVolumeClaim:
          claimName: deepo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: deepo
  namespace: jlab
  labels:
    name: deepo
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: jupyter
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: streamlit
  selector:
    name: deepo

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deepo
  namespace: jlab
spec:
  rules:
  - host: deepo.jlab.14.49.xxx.xxx.xip.io
    http:
      paths:
      - backend:
          serviceName: deepo
          servicePort: 8888
```

참고자료
- https://github.com/ufoym/deepo

**Comment by GunSik2** [comment]
## k8s + gpu-jupyter ( using docker-stacks )

사전작업
- #11 

Jupyter 배포
- longhorn 스토리지클래스 사용 
- jlab 네임스페이스 사용 
- jupyter.jlab.14.49.xxx.xxx.xip.io 호스트명 사용
```
kubectl create ns jlab
kubectl apply -f stacks.yml
```
- stacks.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
  namespace: jlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: jlab
  labels:
    name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jupyter
  template:
    metadata:
      labels:
        name: jupyter
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: jupyter
        image: cschranz/gpu-jupyter:v1.4_cuda-10.1_ubuntu-18.04
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        command:
        - /bin/bash
        - -c
        - |
          jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='xxxx' --notebook-dir='/root'
        volumeMounts:
        - name: jupyter-data
          mountPath: /root
        resources:
          requests:
            memory: 500Mi
            cpu: 250m
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Always
      volumes:
      - name: jupyter-data
        persistentVolumeClaim:
          claimName: jupyter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: jlab
  labels:
    name: jupyter
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: jupyter
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: streamlit
  selector:
    name: jupyter

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter
  namespace: jlab
spec:
  rules:
  - host: jupyter.jlab.14.49.xxx.xxx.xip.io
    http:
      paths:
      - backend:
          serviceName: jupyter
          servicePort: 8888
```

GUP 확인 
- Notebook GPU 확인
```
!nvidia-smi
```


- Tensorflow GPU 확인
```
import keras
import tensorflow as tf

tf.debugging.set_log_device_placement(True)
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

# Create some tensors
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)

print(c)
```

참고자료
- https://github.com/iot-salzburg/gpu-jupyter/

**Comment by GunSik2** [comment]
## 이미지 빌드 

이미지 빌드
- cschranz/gpu-jupyter:v1.4_cuda-10.1_ubuntu-18.04 이미지 기반
- [pyspark-jupyter Docker](https://github.com/jupyter/docker-stacks/tree/master/pyspark-notebook) 기반
```

```

참고 자료
- https://github.com/jupyter/docker-stacks
- https://github.com/iot-salzburg/gpu-jupyter/

**Comment by GunSik2** [comment]
## k8s + gpu-jupyter ( based on docker-stacks )  // Spark 미지원

사전작업
- #11 

Jupyter 배포
- longhorn 스토리지클래스 사용 
- jlab 네임스페이스 사용 
- jupyter.jlab.14.49.xxx.xxx.xip.io 호스트명 사용
```
kubectl create ns jlab
kubectl apply -f stacks.yml
```
- stacks.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
  namespace: jlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: jlab
  labels:
    name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jupyter
  template:
    metadata:
      labels:
        name: jupyter
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: jupyter
        image: cschranz/gpu-jupyter:v1.4_cuda-10.1_ubuntu-18.04
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        command:
        - /bin/bash
        - -c
        - |
          chmod -R 777 /home/jovyan; 
          start.sh jupyter lab --LabApp.token='password' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
        volumeMounts:
        - name: jupyter-data
          mountPath: /home/jovyan
        resources:
          requests:
            memory: 500Mi
            cpu: 250m
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Always
      volumes:
      - name: jupyter-data
        persistentVolumeClaim:
          claimName: jupyter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: jlab
  labels:
    name: jupyter
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: jupyter
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: streamlit
  selector:
    name: jupyter

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter
  namespace: jlab
spec:
  rules:
  - host: jupyter.jlab.14.49.xxx.xxx.xip.io
    http:
      paths:
      - backend:
          serviceName: jupyter
          servicePort: 8888
```

GUP 확인 
- Notebook GPU 확인
```
!nvidia-smi
```

- Tensorflow GPU 확인
```
import keras
import tensorflow as tf

tf.debugging.set_log_device_placement(True)
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

# Create some tensors
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)

print(c)
```
![image](https://user-images.githubusercontent.com/11453229/135207007-54157040-4753-4695-be67-6e6d211e9741.png)


참고자료
- https://github.com/iot-salzburg/gpu-jupyter/
