### ISSUE TITLE
spark-operator 

### ISSUE THREAD

**Issue by GunSik2** [GunSik2/k8s-ai#7]
1. helm repo 등록
helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator

2. operator 설치
helm install my-release spark-operator/spark-operator --namespace spark-operator --create-namespace

3. rbac 설정
kubectl create serviceaccount spark
kubectl create clusterrolebinding spark-role --clusterrole=edit --serviceaccount=default:spark --namespace=default

4. sample 실행
kubectl apply -f spark-pi.yaml

참고자료
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator

**Comment by GunSik2** [comment]
remove operator
```
helm uninstall my-release 
kubectl delete serviceaccounts  my-release-spark-operator  -n spark-operator
kubectl delete serviceaccounts  default  -n spark-operator
```

**Comment by GunSik2** [comment]
spark-pi.yaml
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.1.1"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
  arguments:
    - "100000"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```
